Add support for session and clients.
Ketouem/flask-boto3 pull request #3
Opened 2017-11-13 02:41 UTC by boroivanov

@Ketouem thanks for creating flask-boto3. It's great.

This PR adds support for boto3 sessions and clients. Not all AWS services are supported as resources via boto.

I was trying to use flask-boto3 to connect to codedeploy and codebuild for my app and was getting the following:
```bash
boto3.exceptions.ResourceNotExistsError: The 'codedeploy' resource does not exist.
The available resources are:
   - cloudformation
   - cloudwatch
   - dynamodb
   - ec2
   - glacier
   - iam
   - opsworks
   - s3
   - sns
   - sqs

Consider using a boto3.client('codedeploy') instead of a resource for 'codedeploy'
```

The proposed changes address this issue.

2017-11-13 09:36 UTC, Ketouem requested changes
Looks great ! Could you also edit the unit tests to reflect those changes ?

2017-11-14 05:37 UTC, boroivanov commented
Thanks. I forgot to update those. It's done now. The tests are passing for me.

2017-11-14 09:48 UTC, Ketouem commented
I get some errors when I'm running the tests inside a container
```
======================================================================
ERROR: test_003_pass_credentials_through_app_conf (tests.TestFlaskBoto3Clients)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/sources/tests/__init__.py", line 133, in test_003_pass_credentials_through_app_conf
    b.connections
  File "/sources/flask_boto3.py", line 95, in connections
    ctx.boto3_cns = self.connect()
  File "/sources/flask_boto3.py", line 38, in connect
    sess = boto3.session.Session(**sess_params)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 112, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 695, in get_component
    return self._components.get_component(name)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 889, in get_component
    self._components[name] = factory()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 179, in <lambda>
    lambda:  create_loader(self.get_config_variable('data_path')))
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 259, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 280, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 352, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (default) could not be found
```

it seems that we'll need to create a temp creds file and pass its path to boto3.

2017-11-14 16:21 UTC, boroivanov commented
Thanks for catching this. I thought https://github.com/Ketouem/flask-boto3/pull/3/files#diff-498cf53d35427897613cdfc4b76fc6eaR130 covers that. The test was passing for me. I'll take a look again tonight. I must have missed something.

2017-11-14 16:25 UTC, Ketouem commented
Actually you missed nothing, I'm running the tests inside an environment that is free from any AWS configuration (hence the missing creds file and the error message), so you juste need to adjust the test setup to handle this case. 😃

2017-11-14 16:27 UTC, boroivanov commented
Makes sense. Ok, cool. I'll adjust it when I get back from work. Cheers.

2017-11-15 05:10 UTC, boroivanov commented
@Ketouem, I think we are good now. Could run again on your end and confirm? Thanks

2017-11-15 08:49 UTC, merged

2017-11-15 09:32 UTC, Ketouem commented
Indeed we are 🎉  thanks to your work, I've released the `0.3.0` available on pypi.

2017-11-15 16:15 UTC, boroivanov commented
Great :). Thank you.